name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover

      - name: Package Lambda Function
        run: |
          mkdir package
          pip install -r requirements.txt --target ./package
          cp lambda_function.py ./package/
          cd package
          zip -r ../lambda_function.zip .

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if aws lambda get-function --function-name lambda_function; then
            echo "Updating Lambda function..."
            aws lambda update-function-code --function-name lambda_function --zip-file fileb://lambda_function.zip
          else
            echo "Creating new Lambda function..."
            aws lambda create-function --function-name lambda_function --zip-file fileb://lambda_function.zip --handler lambda_function.lambda_handler --runtime python3.8 --role arn:aws:iam::773021952013:role/test_role_git_actions
          fi
 